name: ServerUtils
author: jlariv11
version: 2.4
main: main.jake.serverutils.ServerUtils
description: Adds useful commands for servers

commands:
  pvp:
    description: Enables or disables pvp for a player or lists the players who have pvp enabled or disabled
    usage: /pvp enable/disable <player> /pvp list
    permission: serverutils.pvp
    permission-message: You don't have permission to use this command
  warp:
    description: Warps to a previously set warp
    usage: /warp [name]
    permission: serverutils.warp
    permission-message: You don't have permission to use this command
  setwarp:
    description: Set a new warp
    usage: /setwarp [name] <public>
    permission: serverutils.setwarp
    permission-message: You don't have permission to use this command
  warps:
    description: Lists all warps available to you
    usage: /warps
    permission: serverutils.listwarp
    permission-message: You don't have permission to use this command
  delwarp:
    description: Deletes a warp
    usage: /delwarp [name]
    permission: serverutils.delwarp
    permission-message: You don't have permission to use this command
  sharewarp:
    description: allow/disalow someone to use a warp
    usage: /sharewarp [add/remove] [player]
    permission: serverutils.sharewarp
    permission-message: You don't have permission to use this command
  xpshare:
    description: Give experience to another player
    usage: /xpshare [player] [levels]
    permission: serverutils.xpshare
    permission-message: You don't have permission to use this command
  tpa:
    description: Request accept and deny teleports
    usage: /tpa <player> /tpa <confirm/deny>
    permission: serverutils.tpa
    permission-message: You don't have permission to use this command

  test:
    description: test
    usage: /test
    permission: serverutils.test
    permission-message: test
